### PR TITLE
6/26/19 deploy multiple sklearn models to gcp

### PR DESCRIPTION
**Pull request by yashvijay**

### CODE REVIEW

**Comment by rsmith49** [comment]
@yashvijay Is there a reason you're adding new files with very similar code instead of reusing code from `notebooks/ML/src`?

**Comment by yashvijay** [comment]
@rsmith49 The new code files I've added under notebooks/ML/multitag/src are for deploying multiple models. The preprocess.py file is the same from the one in notebooks/ML/src, the ensemble.py file is only for deploying multiple models, and the other code files are slightly different. I thought it would be easier to keep the multitag model code separately in another folder.

**Comment by rsmith49** [comment]
I would say probably better for them to refer to the same file, to keep good coding practices of being able to change one thing easily for both scenarios

**Comment by yashvijay** [comment]
@rsmith49 I've removed the older files and added a new GCP directory with better structure. Have changed the setup files for both single model and multi model deployment to refer to the same preprocess file. Let me know if this is good.

**Pull request merged**
